### ISSUE TITLE
禁用扩展后工具栏仍留有图标

### ISSUE THREAD

**Issue by AlwaysWithYou** [shyangs/Meihua-Chinese-Converter#5]
禁用扩展后工具栏仍留有图标，并且左键单击图标可起作用，右键单击扩展图标后浏览器对鼠标点击没了反应。Windows 7 Ultimate x64，32 位的 Firefox 43.0.4 和 Firefox 44，已用空白配置测试。

**Comment by shyangs** [comment]
#### [v2.0-alpha.40](https://github.com/shyangs/Meihua-Chinese-Converter/releases/tag/v2.0-alpha.40)

已修正.
